### ISSUE TITLE
technique : refactor de Datasets

### ISSUE THREAD

**Issue by GuyleneTandeauDeMarsac** [InseeFr/Magma#104]
- enum pour ValidationState
- découpage de DataSetModelSwagger (en fonction des considérations métier) : objet actuellement trop gros
- revisite des tests

**Comment by flo7894** [comment]
retour actuel pour réfléchir sur le découpage

{
  "id": "jd1101",
  "uri": "http://bauhaus/datasets/jd1101",
  "identifier": "DD_BPE_2021",
  "created": "2022-01-04T08:00:00.000",
  "issued": "2022-01-04T08:00:00.000",
  "modified": "2022-01-04T08:00:00.000",
  "disseminationStatus": "Public spécifique",
  "validationState": "Provisoire, jamais publiée",
  "version": "1.0",
  "creator": "DG75-L201",
  "contributor": "DG75-L201",
  "publisher": {
    "id": "Insee",
    "label": [
      {
        "lang": "fr",
        "content": "Institut national de la statistique et des études économiques"
      },
      {
        "lang": "en",
        "content": "National Institute of Statistics and Economic Studies"
      }
    ]
  },
  "title": [
    {
      "lang": "fr",
      "content": "BPE 2021 Ensemble géolocalisé"
    },
    {
      "lang": "en",
      "content": "BPE 2021 Ensemble géolocalisé"
    }
  ],
  "subtitle": [
    {
      "lang": "fr",
      "content": "avec coordonnées XY"
    },
    {
      "lang": "en",
      "content": "with XY coordinates"
    }
  ],
  "abstract": [
    {
      "lang": "fr",
      "content": "La base permanente des équipements (BPE) est une base à vocation statistique."
    },
    {
      "lang": "en",
      "content": "The permanent facilities database (BPE in French) is a statistical database."
    }
  ],
  "description": [
    {
      "lang": "fr",
      "content": "La base permanente des équipements (BPE) est une base à vocation statistique. Elle répertorie un large éventail d'équipements et de services, marchands ou non, accessibles au public sur l'ensemble de la France au 1ᵉʳ janvier de chaque année."
    },
    {
      "lang": "en",
      "content": "The permanent facilities database (BPE in French) is a statistical database. It lists a wide range of facilities and services, both market and non-market, accessible to the public throughout France on 1ᵉʳ January of each year."
    }
  ],
  "scopeNote": [
    {
      "lang": "fr",
      "content": "Message infomatif mis dans le bandeau bleu clair avec un paneau attention sur insee.fr"
    },
    {
      "lang": "en",
      "content": "alert message"
    }
  ],
  "wasGeneratedBy": [
    {
      "id": "s2077",
      "type": "Opération statistique",
      "label": [
        {
          "lang": "fr",
          "content": "Base permanente des équipements 2021"
        },
        {
          "lang": "en",
          "content": "Permanent database of facilities 2021"
        }
      ]
    }
  ],
  "type": [
    {
      "lang": "fr",
      "content": "Données individuelles"
    },
    {
      "lang": "en",
      "content": "Microdata"
    }
  ],
  "archiveUnit": [
    {
      "id": "UA1",
      "label": [
        {
          "lang": "fr",
          "content": "diffusion Insee.fr"
        },
        {
          "lang": "en",
          "content": "Insee.fr dissemination"
        }
      ]
    }
  ],
  "accessRights": [
    {
      "lang": "fr",
      "content": "Libre"
    },
    {
      "lang": "en",
      "content": "Free"
    }
  ],
  "confidentialityStatus": [
    {
      "lang": "fr",
      "content": "Libre"
    },
    {
      "lang": "en",
      "content": "Free"
    }
  ],
  "theme": [
    {
      "uri": "http://bauhaus/concepts/theme/ter1",
      "label": [
        {
          "lang": "fr",
          "content": "Équipements et services à la population"
        },
        {
          "lang": "en",
          "content": "Population facilities and services"
        }
      ],
      "themeTaxonomy": "inseeTheme"
    },
    {
      "uri": "http://bauhaus/concepts/theme/bsn1",
      "label": [
        {
          "lang": "fr",
          "content": "Agriculture"
        },
        {
          "lang": "en",
          "content": "Agriculture"
        }
      ],
      "themeTaxonomy": "inseeTheme"
    },
    {
      "uri": "http://bauhaus/concepts/statisticalDomain/sd1",
      "label": [
        {
          "lang": "fr",
          "content": "1 Statistiques démographiques et sociales"
        },
        {
          "lang": "en",
          "content": "1 Demographic and social statistics"
        }
      ],
      "themeTaxonomy": "classificationOfStatisticalDomain"
    }
  ],
  "landingPage": [
    {
      "lang": "fr",
      "url": "https://www.insee.fr/fr/statistiques/3568638?sommaire=3568656"
    },
    {
      "lang": "en",
      "url": "https://www.insee.fr/fr/statistiques/3568638?sommaire=3568656"
    }
  ],
  "processStep": [
    {
      "lang": "fr",
      "content": "inseeApi"
    },
    {
      "lang": "en",
      "content": "inseeApi"
    }
  ],
  "accrualPeriodicity": {
    "label": [
      {
        "lang": "fr",
        "content": "Annuelle"
      },
      {
        "lang": "en",
        "content": "Annual"
      }
    ]
  },
  "temporal": {
    "startPeriod": "2021",
    "endPeriod": "2021"
  },
  "temporalResolution": [
    {
      "label": [
        {
          "lang": "fr",
          "content": "Annuelle"
        },
        {
          "lang": "en",
          "content": "Annual"
        }
      ]
    },
    {
      "label": [
        {
          "lang": "fr",
          "content": "Mensuelle"
        },
        {
          "lang": "en",
          "content": "Monthly"
        }
      ]
    }
  ],
  "spatial": {
    "id": "FE",
    "label": [
      {
        "lang": "fr",
        "content": "France entière"
      },
      {
        "lang": "en",
        "content": "France"
      }
    ]
  },
  "spatialResolution": [
    {
      "id": "IRIS",
      "label": [
        {
          "lang": "fr",
          "content": "Iris"
        },
        {
          "lang": "en",
          "content": "Iris"
        }
      ]
    }
  ],
  "statisticalUnit": [
    {
      "lang": "fr",
      "content": "Equipement"
    },
    {
      "lang": "en",
      "content": "Equipment"
    }
  ],
  "structure": {
    "id": "dsd1000",
    "dsd": "DSD_BPE_ENSEMBLE_XY"
  },
  "numObservations": 20000,
  "numSeries": 0,
  "uriWithTypeUri": {
    "uri": "http://bauhaus/datasets/jd1101"
  },
  "idWithTypeId": {
    "id": "jd1101"
  }
}
