### ISSUE TITLE
mettre le timbre (dc:creator) en optional dans les services swagger sur les séries

### ISSUE THREAD

**Issue by GuyleneTandeauDeMarsac** [InseeFr/Magma#106]
Pour les services magma sur les séries /operations/series et /operations/series/{id}} mettre un optional pour le propriétaire, afin de retourner avec ces services y compris les séries qui n'ont pas encore de propriétaire renseigné dans RMéS, 

( a termes toutes les séries devront avoir un propriétaire du fait que cette métadonnée est maintenant obligatoire pour les nouvelles séries et que l'on va compléter, coté métier, cette métadonnée sur les séries existantes)

**Comment by dzkwsk** [comment]
Le problème est tjs présent sur /operations/series/  (get all series)

Par contre c'est OK pour /operations/series/{id}}  (get one serie)

**Comment by GuyleneTandeauDeMarsac** [comment]
Les modifs ont été déployées sur http://dvrmeswsgglm001.ad.insee.intra:8080 seulement (plateforme en Debian11).
