### ISSUE TITLE
Ajouter catalogRecord et provider sur get/dataset/{id}

### ISSUE THREAD

**Issue by EmmanuelDemey** [InseeFr/Magma#113]
On a besoin de faire une distinction entre la mise à jour des données et la mise à jour de la description du jeux de données.

**Comment by EmmanuelDemey** [comment]
@flo7894 doit spécifier sur cette carte

**Comment by flo7894** [comment]
Associée à la ressource dcat:Dataset qui décrit un jeu de données, on va avoir une ressource dcat;CatalogRecord qui décrit la gestion de la ressource Dataset. C'est sur ce CatalogRecord qu'on va mettre les dates de création/modification et propriétaire/gestionnaire au sens usuel de Bauhaus

En pj un exemple rdf 

[jd0501.txt](https://github.com/InseeFr/Magma/files/13447001/jd0501.txt)

Au niveau de la sortie json d'un dataset il faudrait ajouter les propriétés suivantes
catalogRecordCreated, catalogRecordModified, catalogRecordCreator, catalogRecordContributor qui correspondent aux propriétés de la ressource CatalogRecord
Le lien entre les deux ressources se fait par le triplet \<uriCatalogRecord\> foaf:primaryTopic \<uriDataset\>
Toutes ces propriétés sont obligatoires.

Au niveau de la ressource dcat:Dataset les triplets suivants ne seront plus présents :
\<uriDataset\> dcterms:created ""^^xsd:dateTime ;
\<uriDataset\> dc:contributor "";
Il faudrait du coup retirer de la sortie json les propriétés "created" et "contributor"


Au niveau de la ressource dcat:Dataset le triplet 
\<uriDataset\> dc:creator ""; 
sera remplacé par :
\<uriDataset\>dcterms:creator \<http://bauhaus/organisations/insee\>; (l'objet peut bouger ce sera pas forcément l'insee mais c'est pour signaler qu'on va on mettre une uri et plus un litteral en objet)
il faudrait garder "creator" dans le json mais faire une sortie similaire à celle qu'on a pour "publisher"
pour cette propriété la cardinalité est 1 - *
*C'est ça qui correspond au provider dans le titre de la carte*

Dernier point tant qu'à toucher la sortie, j'avais oublié une propriété dans ma demande précédente, elle correspond au triplet suivant
\<uriDataset\> insee:spatialTemporal "";
Elle est optionnelle et il faudrait mettre "spatialTemporal" dans la sortie json (ça sert à stocker le millésime de la géographie utilisée)

**Comment by flo7894** [comment]
@HugoBouttes j'ai mis la description pour l'ajout du lignage là :https://github.com/InseeFr/Magma/issues/117
