### ISSUE TITLE
Corriger les champs "creator" et "spatialTemporal" sur get/dataset/{id}

### ISSUE THREAD

**Issue by flo7894** [InseeFr/Magma#130]
Dans la sortie json on a actuellement : 

```
 "spatialTemporal": {
    "spatialTemporal": "2020"
  }
```

Il faudrait remplacer par

```
 "spatialTemporal": "2020"
```

Pour le champ creator on a  :

```
"creator": [
    "Insee"
  ]
```

Il faudrait remplacer par (ce qui est fait pour publisher, mais en gardant l'array parce qu'on a potentiellement plusieurs creator)

```
"creator": [
 {
    "id": "Insee",
    "label": [
      {
        "lang": "fr",
        "content": "Institut national de la statistique et des études économiques"
      },
      {
        "lang": "en",
        "content": "National Institute of Statistics and Economic Studies"
      }
    ]
  }
]
```

**Comment by EmmanuelDemey** [comment]
@GuyleneTandeauDeMarsac @JeromeMBourgeois à la demande de @flo7894 est-il possible de la mettre en production ?
