### ISSUE TITLE
ajouter une propriété "name" get/concept/{id}

### ISSUE THREAD

**Issue by flo7894** [InseeFr/Magma#87]
Il s'agit d'un champ optionnel sur les concepts pour gérer les règles de nommage pour les projets de diffusion.

Au niveau rdf on aura :

- \<uriConcept\> adms:identifier \<uriADMSIdentifiant\> dans le graphe des définitions de concept
- et dans un graphe dédié aux identifications alernatives (<http://rdf.insee.fr/graphes/adms>)
  - \<uriADMSIdentifiant\> a adms:Identifier
  - \<uriADMSIdentifiant\> skos:notation "ABCD"

Si ces triplets sont présents, on aura dans le json du concept la propriété suivante à la racine
{
...
"name": "ABCD"
}

**Comment by flo7894** [comment]
il semble y avoir une régression depuis jeudi dernier, avec le fichier ci-dessous, j'ai une erreur 500 sur c0951 et c0952, et pr c0950 et c0953 la propriété conceptsSDMX sort en double dans le json

[test_concept_20230926.txt](https://github.com/InseeFr/Magma/files/12724692/test_concept_20230926.txt)

**Comment by HugoBouttes** [comment]
On est en train de corriger ça. Mais est-ce normal d'avoir plusieurs name pour c0951 par exemple ?

**Comment by flo7894** [comment]
Non il ne devrait y avoir qu'un seul name. Si on bascule sur du plusieurs, il faudra qu'on créé des schemeIdentifier, pour n'avoir qu'un name par scheme, mais pour le moment on reste simple.
Théoriquement on a un triplets du concept vers l'identifiantAdms dans le graphes definitions : <uriConcept> adms:identifier <uriIdentifiantADMS>, puis dans le graphe adms on a un triplet de l'identifiantAdms vers le name : <uriIdentifantADMS> skos:notation "_NAME_"
Du coup ça devrait pas sortir en doublon
Et c'est optionnel, seul les concepts utilisés dans les structures de données ou les variables auront un name
