### ISSUE TITLE
Jeu de données pour Magma - endpoint dataset et structure composant

### ISSUE THREAD

**Issue by EmmanuelDemey** [InseeFr/Magma#93]
@flo7894  nous venons de déployer tous les devs réalisés pour Magma par @HugoBouttes . Mais pour l'instant les endpoints retournent rien, car nous manquons de données. 

C'est à de les fournir ?  notamment les datasets. (car pour les structures et composants, le module n'est pas encore en production)

**Comment by flo7894** [comment]
@EmmanuelDemey, @HugoBouttes 
Le projet Melodi va mettre en bêta son catalogue des jeux de données dans un mois ou deux, je dois récupérer les descriptions des jeux de données qu'ils comptent mettre en démonstration, pour les intégrer dans nos bases rdf
