### ISSUE TITLE
Adapter GET/listeCode/{id}

### ISSUE THREAD

**Issue by HugoBouttes** [InseeFr/Magma#97]
Il semble y avoir un problème sur la méthode.
L'ensemble des codes de la listes devrait être listés comme un array avec une propriété "codes", pour chaque code en cas de présence d'un prédicat skos:exactMatch (ou skos:closeMatch) du code vers un code alternatif, on devrait avoir un array sur le code avec la propriété "codesEquivalents"

En pj un exemple de fichier trig d'une code liste, et le fichier json qu'on attendrait en retour
[JSON-recette-liste-2023-09-22.txt](https://github.com/InseeFr/Magma/files/12746659/JSON-recette-liste-2023-09-22.txt)
[TRIG-recette-liste-2023-09-22.txt](https://github.com/InseeFr/Magma/files/12746660/TRIG-recette-liste-2023-09-22.txt)

**Comment by HugoBouttes** [comment]
[TRIG-recette-liste-2023-09-22 v2.txt](https://github.com/InseeFr/Magma/files/12749152/TRIG-recette-liste-2023-09-22.v2.txt)

**Comment by flo7894** [comment]
Il reste un problème sur la récupération des codes équivalents. Quant on récupère la CL_FREQ on a une modalité avec un code "B" pour la fréquence "Quotidienne – jours ouvrés" qui indique des codes équivalents "Bbis" et "Bter" qui sont probablement ceux de la liste de test de cette carte.

Une modalité (skos:Concept) d'une liste de code (skos:ConceptScheme) a son code stockée via la propriété skos:notation mais le ltiéral derrière skos:notation n'est pas unique dans le graphe, deux modalités d'une liste de codes ne devraient pas avoir le même code mais deux modalités dans deux listes de codes différentes peuvent avoir le même code.

En regardant la requête utilisée par magma,

SELECT ?match ?matchNotation
FROM <${CONCEPTS_GRAPH}>
WHERE {
    ?concept skos:notation "${CONCEPT_ID}" .
    ?concept skos:exactMatch | skos:closeMatch ?match .
    ?match skos:notation ?matchNotation .
}

Il manque une vérification que le ?concept est bien celui qui est dans la liste de codes qu'on demande initialement à l'API (on a un lien entre le concept et sa liste de concept via le prédicat skos:inScheme)
Ou alors il faudrait travailler directement à partir de l'uri du concept plutôt que d'utiliser sa notation en paramètre

Les concepts équivalents (?match) n'ont pas nécessité d'être dans le même conceptScheme du coup pour eux il n'y aurait pas de vérification supplémentaire à faire

**Comment by EmmanuelDemey** [comment]
@GuyleneTandeauDeMarsac et @HugoBouttes doivent vérifier que ce ticket a été déployé ou pas.

**Comment by GuyleneTandeauDeMarsac** [comment]
@flo7894  On vient de le déployer en QF
