### ISSUE TITLE
completer get/dataset/{id}

### ISSUE THREAD

**Issue by flo7894** [InseeFr/Magma#99]
Ajout de champs pour compléter la description des datasets

[TRIG-jeu-de-donnees-20230929.txt](https://github.com/InseeFr/Magma/files/12881863/TRIG-jeu-de-donnees-20230929.txt)

[JSON-jeu-de-donnees-20230929.txt](https://github.com/InseeFr/Magma/files/12765250/JSON-jeu-de-donnees-20230929.txt)

**Comment by HugoBouttes** [comment]
@flo7894 Est-ce que tu saurais me dire quelles sont les variables à mettre en OPTIONAL dans notre nouvelle requête SPARQL ?

**Comment by GuyleneTandeauDeMarsac** [comment]
@flo7894 avec Hugo, on a quelques questions pour préciser la spec
- on a corrigé astract en abstract dans le JSON, c'est bien cela ?
- dct:temporal : au lieu d'avoir 2 valeurs "2021" (pour startPeriod et endPeriod) on a _:node1 et _:node3 => un problème dans le Trig ?
- temporalResolution : peut-il y en avoir plusieurs (car dans le JSON, on a un JSON Array) ? ou bien est-ce une erreur de spec ?
- même question pour archiveUnit et spatialResolution
- pour theme, peux-tu nous confirmer qu'il faut retirer uri ? par ailleurs, l'un des deux thèmes (dcat:theme) présents en base est vide, et l'autre ne semble pas correspondre au json (à quoi correspond themeTaxonomy ?)
- disseminationStatus : dans le trig, l'objet n'a pas de data ("no data available in table")

**Comment by flo7894** [comment]
@hugo les préidcats systématiquement attendu sont dcterms:identifier, dcterms:created, dcterms:modified, insee:validationState, insee:disseminationStatus, dc:creator, dc:contributor et dcterms:title. Tout le reste est optionel

**Comment by flo7894** [comment]
@HugoBouttes Les prédicats attendus sont dcterms:identifier, dcterms:created, dcterms:modified, insee:validationState, insee:disseminationStatus, dc:creator, dc:contributor et dcterms:title.
Le reste est optionnel.

**Comment by flo7894** [comment]
@GuyleneTandeauDeMarsac 
- oui merci pour la correction sur abstract
- dans le trig il y a un noeud blanc pour encapsuler les "dates" de début et de fin, en faisant <uriJeuDeDonnees> dcterms:temporal/dcat:startDate ?dateDebut on devrait attraper le 2021
- la cardinalité n'est pas encore tout à fait certaine, dans le doute on mettrait bien un array sur les trois pour le moment
- pour theme, il manque des données, je vais les mettre, le themeTaxonomy va correspondre à l'identifiant du conceptScheme qui contient le theme du coup <uriTheme> skos:inScheme/skos:notation ?themeTaxonomy devrait retourner ce qui est attendu quand les données seront corrigées
- je pense que c'est parce l'ontologie insee n'est pas dans la base (https://github.com/InseeFr/Ontologies/blob/master/insee-base.ttl) il faudrait prendre le prefLabel@fr

**Comment by flo7894** [comment]
Les triplets complémentaires pour gérer les thèmes

[TRIG-complements-pour-themes.txt](https://github.com/InseeFr/Magma/files/12881765/TRIG-complements-pour-themes.txt)

L'ontologie insee peut être chargée dans un graphe à part http://rdf.insee.fr/graphes/ontologies/insee/base

**Comment by GuyleneTandeauDeMarsac** [comment]
@flo7894 il me semble qu'il y avait des coquilles dans https://github.com/InseeFr/Ontologies/blob/master/insee-base.ttl. J'ai ajouté des points-virgules (lignes 49-60-73-93-99) et le terme "a" ligne 217 pour pouvoir l'importer. Je te le joins à toute fin utile.

[ontologies_corrige.txt](https://github.com/InseeFr/Magma/files/12890973/ontologies_corrige.txt)

**Comment by GuyleneTandeauDeMarsac** [comment]
Spec :

[json-dataset.odt](https://github.com/InseeFr/Magma/files/12894126/json-dataset.odt)

**Comment by HugoBouttes** [comment]
SPEC : 
[json-dataset.odt](https://github.com/InseeFr/Magma/files/12894261/json-dataset.odt)
